import os
from dotenv import load_dotenv

load_dotenv()
class Config:
    SECRET_KEY = os.getenv("SECRET_KEY")
    SQLALCHEMY_DATABASE_URI = os.getenv("SQLALCHEMY_DATABASE_URI")
    # JWT Configurations
    JWT_SECRET_KEY = os.getenv("JWT_SECRET_KEY", SECRET_KEY or "fallback_jwt_secret_key")
    from datetime import timedelta
    JWT_ACCESS_TOKEN_EXPIRES = timedelta(hours=1)
    JWT_REFRESH_TOKEN_EXPIRES = timedelta(days=1)
    JWT_ALGORITHM = "HS256"
    OTP_EXPIRATION_DAYS = 7
    # Flask-Mail Configurations

    #the mail server used to send emails
    MAIL_SERVER = os.getenv("MAIL_SERVER", "smtp.gmail.com")
    #the port used to connect to the mail server
    MAIL_PORT = int(os.getenv("MAIL_PORT", 587))
    #encrypts the connection to the maail srever
    MAIL_USE_TLS = os.getenv("MAIL_USE_TLS", "True").lower() == "true"
    #Disable SSL encyption since TLS  is already used
    MAIL_USE_SSL = os.getenv("MAIL_USE_SSL", "False").lower() == "true"
    #the email account used to authenticate with the mail server
    MAIL_USERNAME = os.getenv("MAIL_USERNAME")
    ## the app password generated by Google for the email account
    MAIL_PASSWORD = os.getenv("MAIL_PASSWORD")
    # the email address that appears in the "From" field when sending emails
    MAIL_DEFAULT_SENDER = os.getenv("MAIL_DEFAULT_SENDER")

    # groq Configurations
    GROQ_API_KEY = os.getenv("GROQ_API_KEY")


    os.environ["LANGCHAIN_TRACING_V2"] = "true"
    os.environ["LANGCHAIN_API_KEY"] = os.getenv("LANGCHAIN_API_KEY")
    os.environ["LANGCHAIN_PROJECT"] = "AI_Assistant"

 

    CHROMA_API_KEY = os.getenv("CHROMA_API_KEY")
    CHROMA_TENANT = os.getenv("CHROMA_TENANT")
    CHROMA_DATABASE = os.getenv("CHROMA_DATABASE")  




